In [38]:
import numpy as np
from numpy import random as nprnd
import random as rnd
import pandas as pd
import string as str
from math import *
import itertools

#scipy stat
import scipy.stats as ss
from scipy import stats
from scipy.stats import linregress,norm, kurtosis, moment,iqr,binom, binomtest,gmean
from scipy.stats import expon,zscore,zmap
from scipy.stats import t,ttest_ind
from scipy.stats import f,f_oneway
from scipy.stats import boxcox
from scipy.stats import skewnorm,skew
from scipy.stats import pearsonr
from scipy.linalg import toeplitz
from scipy.interpolate import CubicSpline
#scipy signals library
from scipy import signal
#scipy calculus library
import scipy.integrate as spi



#scipy chi
from scipy.stats import chi,chi2_contingency,chi2

import math

import os
import time

import csv

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.style as style

import seaborn as sns
# Pkg import Date Time
from datetime import datetime
from datetime import timedelta
from pandas.tseries.offsets import Hour, Minute
from pandas.tseries.offsets import Day, MonthEnd
import pytz
from pandas.tseries.frequencies import to_offset
#import arviz as az
import plotly
from sympy import symbols, Eq, solve
import re #extract cofficient

###################################################
'''Statemodels'''
###################################################
# # Ordinary Least Squares
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.formula.api import ols
import statsmodels.stats.power as smp
from statsmodels.regression.linear_model import OLS
from statsmodels.stats.outliers_influence import OLSInfluence
from statsmodels.stats.stattools import durbin_watson,omni_normtest,\
                                        jarque_bera
from patsy import dmatrices,dmatrix

from zlib import crc32
import hashlib

###################################################
'''sklearn'''
###################################################
# model_selection
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold, StratifiedKFold, StratifiedShuffleSplit
from sklearn.model_selection import learning_curve

# Multiclass
from sklearn.multiclass import OneVsOneClassifier,OneVsRestClassifier

# Base
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.base import clone

# preprocessing
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures,label_binarize

# pipeline
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

# datasets
from sklearn.datasets import fetch_openml
from sklearn.datasets import make_blobs
from sklearn import datasets
from sklearn.datasets import make_classification
from sklearn.datasets import load_iris
from sklearn.datasets import load_sample_image

# metrics

from sklearn.metrics import root_mean_squared_error

from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.metrics import confusion_matrix,precision_score,\
                            recall_score,f1_score,\
                            classification_report, accuracy_score,\
                            precision_recall_curve,\
                            roc_curve,auc, roc_auc_score,\
                            ConfusionMatrixDisplay,\
                            root_mean_squared_error    
                            
# neural_network
from sklearn.neural_network import MLPClassifier,\
                                   MLPRegressor,\
                                   BernoulliRBM

# tree
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

# linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import Ridge
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Perceptron
#SVM
from sklearn.svm import SVC
from sklearn.svm import LinearSVC

from graphviz import Source

#ensemble
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier

#decomposition
from sklearn.decomposition import PCA

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

from sklearn.cluster import MiniBatchKMeans

import tensorflow as tf
from tensorflow import keras

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tarfile
import urllib.request
#====================================
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import regularizers
from tensorflow.keras import initializers

from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model
# layers
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
#activations
from tensorflow.keras.activations import sigmoid
#utils
from tensorflow.keras.utils import to_categorical

#callbacks
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.callbacks import LambdaCallback
from tensorflow.keras.callbacks import TerminateOnNaN
from tensorflow.keras.callbacks import CSVLogger
from tensorflow.keras.callbacks import LearningRateScheduler
from tensorflow.keras.callbacks import ReduceLROnPlateau



import sys
from copy import deepcopy

import kagglehub
# =====================================
# caution: path[0] is reserved for script path (or '' in REPL)
sys.path.insert(1, r'C:\Users\TODO\Desktop\Abhi\AI\AI\Math\Hands-On\statemodelsStudy')
from olsRegressionAnalysis import dispAnalysisOfVariance, tableDispFormatt,getInvOfProductMat,\
                                  getRegressionEqn,\
                                  dispReghressionAnalysis,norm_scalling,getCorrelation,\
                                  get_variance_inflation_factors,goodnessOfFitTestOfParams



In [39]:
path = os.path.join(os.getcwd(), 'mnist_784.csv')
df = pd.read_csv(path)
print(f"total Pixal Len: {len(df.columns.values)}")
print(df.shape[0], 'Total Pixal 28x28')


total Pixal Len: 785
70000 Total Pixal 28x28


In [40]:
df = df.loc[0:19,:]
X = df.drop('class',axis=1)
y = df['class']
y_one_hot = to_categorical(y, num_classes=10)
print(f'x shape:{X.shape} y shape {y.shape} y_one_hot {y_one_hot.shape}')


x shape:(20, 784) y shape (20,) y_one_hot (20, 10)


In [41]:
inputs = Input(shape=(28, 28, 1), name="image_input")
inputs = Input(shape=(784,), name="input_layer")
inputs.shape

(None, 784)

In [51]:
l1 = layers.Dense(units = 160, 
                  name = 'layer_1',
                  activation="relu",
                  use_bias=True,
                  kernel_initializer="glorot_uniform",
                  bias_initializer="zeros"
                  )(inputs)
l2 = layers.Dense(units = 40, name = 'layer_2',activation="relu",use_bias=True,kernel_initializer="glorot_uniform",
             bias_initializer="zeros")(l1)
outputs = layers.Dense(units = 10, name = 'out_layer',activation="softmax",use_bias=True,kernel_initializer="glorot_uniform",
             bias_initializer="zeros")(l2)
model = keras.Model(inputs=inputs, outputs=outputs)

In [43]:
model.get_layer(index=1)

<Dense name=layer_1, built=True>

In [44]:
print(f'Input shape:{inputs.shape}')
print(f'l1 shape:{l1.shape}')
print(f'l2 shape:{l2.shape}')
print(f'outputs shape:{outputs.shape}')

Input shape:(None, 784)
l1 shape:(None, 160)
l2 shape:(None, 40)
outputs shape:(None, 10)


In [50]:
# 
layer = model.get_layer("layer_1")
# Get weights
weights = layer.get_weights()
kernel, bias = weights[0], weights[1]
print("Kernel shape:", kernel.shape,'X shape: ',X.shape)  # (784, 128)
print("Bias shape:", bias.shape,type(bias))      # (128,)
print(f'Shape X@W {(X @ kernel).shape} baise shape {bias.shape}')
print(f'final shape: {((X @ kernel) + bias).shape}')

Kernel shape: (784, 160) X shape:  (20, 784)
Bias shape: (160,) <class 'numpy.ndarray'>
Shape X@W (20, 160) baise shape (160,)
final shape: (20, 160)


In [ ]:
# Access first Dense layer
layer = model.get_layer("layer_2")
# Get weights
weights = layer.get_weights()
kernel, bias = weights[0], weights[1]
print("Kernel shape:", kernel.shape)  # (784, 128)
print("Bias shape:", bias.shape)      # (128,)

Kernel shape: (160, 40)
Bias shape: (40,)


In [ ]:
# Access first Dense layer
layer = model.get_layer("out_layer")
# Get weights
weights = layer.get_weights()
kernel, bias = weights[0], weights[1]
print("Kernel shape:", kernel.shape)  # (784, 128)
print("Bias shape:", bias.shape)      # (128,)
for i, w in enumerate(weights):
        print(f"  Weight {i} shape: {w.shape}")
        wr = np.round(w,3)[0:9]
        print(wr)   # actual matrix values

print(np.round(bias,3))

Kernel shape: (40, 10)
Bias shape: (10,)
  Weight 0 shape: (40, 10)
[[-0.001 -0.061  0.292 -0.312 -0.321  0.041  0.104  0.131 -0.304 -0.261]
 [ 0.146  0.288  0.26   0.15   0.268 -0.035  0.186  0.301 -0.078 -0.002]
 [-0.153 -0.136  0.262  0.318  0.118  0.167 -0.193  0.026 -0.005  0.057]
 [-0.346 -0.061 -0.07  -0.265  0.242 -0.177 -0.232  0.247 -0.229  0.239]
 [ 0.174 -0.292  0.063 -0.167  0.343 -0.031  0.241 -0.054 -0.195  0.094]
 [ 0.206 -0.051 -0.2   -0.173 -0.061  0.113  0.112 -0.183 -0.246 -0.233]
 [ 0.125 -0.269 -0.301  0.239  0.223 -0.154 -0.12   0.024  0.092 -0.106]
 [ 0.171  0.136 -0.082 -0.01  -0.173 -0.036 -0.059 -0.141  0.143  0.128]
 [-0.13  -0.101 -0.283  0.256 -0.227  0.037 -0.148 -0.055  0.245  0.331]]
  Weight 1 shape: (10,)
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Get the total number of layers
total_layers = len(model.layers)
# Get the maximum valid index
max_index = total_layers - 1
print(f"Total number of layers in the model: {total_layers}")
print(f"The maximum layer index is: {max_index}")
# You can now iterate through all layers by index
print("\nLayer details:")
for i in range(total_layers):
    layer = model.get_layer(index=i)
    # 2. The layer is built, so we can immediately check initial random weights
    initial_weights = layer.get_weights()
    print(f"Number of weight tensors returned: {len(initial_weights)}")    
    print(f"Index {i} Layer Name: {layer.name}, Type: {type(layer).__name__}")
    if i > 0:
        if len(weights) > 0:
            kernel, bias = weights[0], weights[1]
            print("Kernel shape:", kernel.shape)  # (784, 128)
            print("Bias shape:", bias.shape)      # (128,)
    




Total number of layers in the model: 4
The maximum layer index is: 3

Layer details:
Number of weight tensors returned: 0
Index 0 Layer Name: input_layer, Type: InputLayer
Number of weight tensors returned: 2
Index 1 Layer Name: layer_1, Type: Dense
Kernel shape: (40, 10)
Bias shape: (10,)
Number of weight tensors returned: 2
Index 2 Layer Name: layer_2, Type: Dense
Kernel shape: (40, 10)
Bias shape: (10,)
Number of weight tensors returned: 2
Index 3 Layer Name: out_layer, Type: Dense
Kernel shape: (40, 10)
Bias shape: (10,)


In [ ]:
model.compile(
    optimizer = 'Adam',
    # ================ Loss & Loss weight ==========================================
    loss         = 'CategoricalCrossentropy',
    loss_weights = None,# assign nothing for loss weight value
    # ==============================================================================
    metrics=['Accuracy'],
    
)

In [ ]:
X.shape,y.shape

((20, 784), (20,))

In [ ]:
history = model.fit(x = X, y = y_one_hot, 
                    batch_size = 2,
                    epochs=20,
                    verbose = 1,
                    callbacks = None, #importent for expert user                                   
)

Epoch 1/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - Accuracy: 0.0141 - loss: 77.7580      
Epoch 2/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - Accuracy: 0.4749 - loss: 25.4642 
Epoch 3/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - Accuracy: 0.8273 - loss: 2.7299     
Epoch 4/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - Accuracy: 0.8534 - loss: 4.4980     
Epoch 5/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 1.0000 - loss: 8.4711e-05 
Epoch 6/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 0.8623 - loss: 0.5013 
Epoch 7/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 1.0000 - loss: 1.3420e-04 
Epoch 8/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 1.0000 - loss: 0.0013     
Epoch 9/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - Accuracy: 1.0000 - loss: 9.4795e-04 
Epoch 10/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - Accuracy: 1.0000 - loss: 9.1227e-06 
Epoch 11/20
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - Accuracy: 1.0000 - loss: 2.1990e-06 
Epoch 12/20
10/10 ━━━━━━

In [ ]:
# Access first Dense layer
layer = model.get_layer("out_layer")
# Get weights
weights = layer.get_weights()
kernel, bias = weights[0], weights[1]
print("Kernel shape:", kernel.shape)  # (784, 128)
print("Bias shape:", bias.shape)      # (128,)
for i, w in enumerate(weights):
        print(f"  Weight {i} shape: {w.shape}")
        wr = np.round(w,3)[0:9]
        print(wr)   # actual matrix values
print(np.round(bias,3))


Kernel shape: (40, 10)
Bias shape: (10,)
  Weight 0 shape: (40, 10)
[[-0.006 -0.06   0.283 -0.309 -0.319  0.057  0.106  0.126 -0.307 -0.26 ]
 [ 0.139  0.286  0.262  0.147  0.267 -0.022  0.195  0.292 -0.084 -0.005]
 [-0.157 -0.129  0.255  0.32   0.119  0.184 -0.207  0.03  -0.008  0.054]
 [-0.347 -0.058 -0.077 -0.267  0.247 -0.164 -0.235  0.251 -0.229  0.235]
 [ 0.174 -0.292  0.063 -0.161  0.343 -0.031  0.241 -0.054 -0.195  0.088]
 [ 0.203 -0.05  -0.202 -0.167 -0.056  0.126  0.116 -0.187 -0.251 -0.238]
 [ 0.12  -0.26  -0.299  0.226  0.227 -0.142 -0.113  0.017  0.082 -0.106]
 [ 0.161  0.137 -0.077 -0.011 -0.17  -0.029 -0.048 -0.15   0.142  0.126]
 [-0.141 -0.105 -0.283  0.259 -0.219  0.051 -0.15  -0.057  0.249  0.329]]
  Weight 1 shape: (10,)
[-0.006  0.004 -0.005 -0.002  0.001  0.017  0.008 -0.004 -0.005]
[-0.006  0.004 -0.005 -0.002  0.001  0.017  0.008 -0.004 -0.005 -0.003]
