In [1]:
import numpy as np
from numpy import random as nprnd
import random as rnd
import pandas as pd
import string as str
from math import *

#scipy stat
import scipy.stats as ss
from scipy import stats
from scipy.stats import linregress,norm, kurtosis, moment,iqr,binom, binomtest,gmean
from scipy.stats import expon,zscore,zmap
from scipy.stats import t,ttest_ind
from scipy.stats import f,f_oneway
from scipy.stats import boxcox
from scipy.stats import pearsonr
#scipy signals library
from scipy import signal
#scipy calculus library
import scipy.integrate as spi



#scipy chi
from scipy.stats import chi,chi2_contingency,chi2

import math

import os
import time

import csv

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.style as style
import seaborn as sns
# Pkg import Date Time
from datetime import datetime
from datetime import timedelta
from pandas.tseries.offsets import Hour, Minute
from pandas.tseries.offsets import Day, MonthEnd
import pytz
from pandas.tseries.frequencies import to_offset
#import arviz as az
import plotly
from sympy import symbols, Eq, solve
import re #extract cofficient

###################################################
'''sklearn'''
###################################################
# # Ordinary Least Squares
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.formula.api import ols
from statsmodels.stats.stattools import durbin_watson
from patsy import dmatrices

from zlib import crc32
import hashlib

###################################################
'''sklearn'''
###################################################
# model_selection
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import KFold, StratifiedKFold, StratifiedShuffleSplit
from sklearn.model_selection import learning_curve

# Multiclass
from sklearn.multiclass import OneVsOneClassifier

# Base
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.base import clone

# preprocessing
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures

# pipeline
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

# datasets
from sklearn.datasets import fetch_openml
from sklearn.datasets import make_blobs
from sklearn import datasets
from sklearn.datasets import make_classification
from sklearn.datasets import load_iris
from sklearn.datasets import load_sample_image

# metrics
try:
    from sklearn.metrics import root_mean_squared_error
except ImportError:
    from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix,precision_score,\
                            recall_score,f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.metrics import ConfusionMatrixDisplay                         

# tree
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz

# linear_model
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import Ridge
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import LogisticRegression
#SVM
from sklearn.svm import SVC
from sklearn.svm import LinearSVC

from graphviz import Source

#ensemble
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.ensemble import BaggingClassifier

#decomposition
from sklearn.decomposition import PCA

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

from sklearn.cluster import MiniBatchKMeans

import tensorflow as tf
from tensorflow import keras

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tarfile
import urllib.request
#====================================
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import initializers
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.activations import sigmoid

import sys
from copy import deepcopy

import kagglehub
# =====================================


#### How to select Input Shape

Input shape dependent on "How many number of feature in your data set". Let dataset Delivery time data. This data set have onle two feature i.e. ***NumCase_X1, Dist_X2***  and one output ***DlvrTime_Y***.

So number of feature = 2
Number of neuron for 1st inpult layer = 



In [2]:
X = np.array([-1, -5, 8, 3, 5]).reshape(5, 1)
y = X / 10
IN = Input(shape=(X.shape[1],))
# kernal initilazion by 1
arr = np.array([1,2]).reshape(1, 2)
val = initializers.Constant(value=arr)
VL = val(shape=(1, 2))

h1 = Dense(units = 2,kernel_initializer=VL,activation = 'sigmoid',name='dense_1')(IN)
arr = np.array([1,3]).reshape(2, 1)
val = initializers.Constant(value=arr)
VL = val(shape=(2, 1))
OUT = Dense(units = 1,kernel_initializer=VL,activation = 'relu',name='dense_2')(h1)

model = Model(IN, OUT)

# Create another model that outputs the intermediate layer
intermediate_layer_model = Model(
    inputs=model.input, outputs=model.get_layer('dense_1').output)

hidden1 = model.layers[1]
w,b = hidden1.get_weights()
print("Weights:", w,w.shape)

hidden1 = model.layers[2]
w,b = hidden1.get_weights()
print("Weights:", w,w.shape)

Weights: [[1. 2.]] (1, 2)
Weights: [[1.]
 [3.]] (2, 1)


In [3]:
#intermediate_layer_model.summary()
intermediate_output = intermediate_layer_model.predict(X)
print("Intermediate Layer Output:\n", intermediate_output)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Intermediate Layer Output:
 [[2.6894140e-01 1.1920294e-01]
 [6.6928524e-03 4.5397861e-05]
 [9.9966466e-01 9.9999988e-01]
 [9.5257413e-01 9.9752736e-01]
 [9.9330717e-01 9.9995458e-01]]


In [4]:
model.compile(loss="sparse_categorical_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])
history = model.fit(X, y, epochs=10,verbose=0)

### 2D feature example

In [5]:
#Create numpy array 1 to 18 1D
X = np.random.randint(-1, 19,18).reshape(9, 2)
y = X[:, 0] + X[:, 1]


In [6]:
IN = Input(shape=(X.shape[1],))

# kernal weight initilazion by 1
# weight shape = (f,u), where f = number of feature, u = number of neuron
arr = np.array([1,2,1,2,1,2]).reshape(2, 3)
val = initializers.Constant(value=arr)
VL = val(shape=(2, 3))
#initilazion of baise, 
# Bias is the linear array of shape (u,)
# where u = number of neuron in the layer
bias_arr = np.array([1,2,1])
BS = initializers.Constant(value=bias_arr)

H_1 = Dense(units = 3,kernel_initializer=VL,bias_initializer=BS,activation = 'sigmoid',name='dense_1')(IN)

# for next layer f = 3, u = 1
arr = np.array([1,3,4]).reshape(3, 1)
val = initializers.Constant(value=arr)
VL = val(shape=(3, 1))

bias_arr = np.array([5])
BS = initializers.Constant(value=bias_arr)

OUT = Dense(units = 1,kernel_initializer=VL,bias_initializer=BS,activation = 'sigmoid',name='dense_2')(H_1)

model = Model(IN, OUT)

In [7]:
model.summary()
# print layer
print(model.layers[0])
print(model.layers[1])
print(model.layers[2])

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 2)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

<InputLayer name=input_layer_1, built=True>
<Dense name=dense_1, built=True>
<Dense name=dense_2, built=True>


In [8]:
# Get H_1 & OUT weights
hidden1 = model.layers[1]
w,b = hidden1.get_weights()
print("Weights of hidden 1 layer:\n", w,"and weight shape: \n",w.shape)
print("Bias of hidden 1 layer :\n",b,"\nBias Shape:\n",b.shape)
out_layer = model.layers[2]
w,b = out_layer.get_weights()
print("Weights of Outpu layer:\n", w,"and weight shape: \n",w.shape)
print("Bias of Outpu layer :\n",b,"\nBias Shape:\n",b.shape)

Weights of hidden 1 layer:
 [[1. 2. 1.]
 [2. 1. 2.]] and weight shape: 
 (2, 3)
Bias of hidden 1 layer :
 [1. 2. 1.] 
Bias Shape:
 (3,)
Weights of Outpu layer:
 [[1.]
 [3.]
 [4.]] and weight shape: 
 (3, 1)
Bias of Outpu layer :
 [5.] 
Bias Shape:
 (1,)


### Weight and bais INIT for n feature and s samples

In [9]:
# Create Numpy array m rows,n columns, and s sampls
def create_numpy_array(m, n):
    """
    Create a numpy array with m rows, n columns, and s samples.
    """
    return np.random.randint(0, 10, (m, n))
X = create_numpy_array(30, 5)
y = X[:, 0] + X[:, 1]
X.shape, y.shape


((30, 5), (30,))

In [10]:
IN = Input(shape=(X.shape[1],))
f = X.shape[1]  # number of features
u = 10 # number of neurons in the layer
# kernal weight initilazion by 1
# weight shape = (f,u), where f = number of feature, u = number of neuron
# 
arr = create_numpy_array(f, u)
val = initializers.Constant(value=arr)
VL = val(shape=(f, u))
#initilazion of baise, 
# Bias is the linear array of shape (u,)
# where u = number of neuron in the layer
bias_arr = np.array([1,2,1,2,1,2,1,2,1,2])
BS = initializers.Constant(value=bias_arr)

H_1 = Dense(units = u,kernel_initializer=VL,bias_initializer=BS,activation = 'sigmoid',name='dense_1')(IN)

f = u
u = 3

arr = create_numpy_array(f, u)
val = initializers.Constant(value=arr)
VL = val(shape=(f, u))
#initilazion of baise, 
# Bias is the linear array of shape (u,)
# where u = number of neuron in the layer
bias_arr = np.array([1,2,1])
BS = initializers.Constant(value=bias_arr)

H_2 = Dense(units = u,kernel_initializer=VL,bias_initializer=BS,activation = 'sigmoid',name='dense_2')(H_1)

f = u
u = 1

arr = create_numpy_array(f, u)
val = initializers.Constant(value=arr)
VL = val(shape=(f, u))
#initilazion of baise, 
# Bias is the linear array of shape (u,)
# where u = number of neuron in the layer
bias_arr = np.array([7])
BS = initializers.Constant(value=bias_arr)

OUT = Dense(units = u,kernel_initializer=VL,bias_initializer=BS,activation = 'sigmoid',name='dense_3')(H_2)

In [11]:
model = Model(IN, OUT)
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_2 (InputLayer)      │ (None, 5)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            33 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
# Get H_1 & OUT weights, Remember @0 always Inputlayer
hidden1 = model.layers[1]
w,b = hidden1.get_weights()
print("Weights of hidden 1 layer:\n", w,"and weight shape: \n",w.shape)
print("Bias of hidden 1 layer :\n",b,"\nBias Shape:\n",b.shape)

hidden2 = model.layers[2]
w,b = hidden2.get_weights()
print("Weights of hidden 2 layer:\n", w,"and weight shape: \n",w.shape)
print("Bias of hidden 2 layer :\n",b,"\nBias Shape:\n",b.shape)

out_layer = model.layers[3]
w,b = out_layer.get_weights()
print("Weights of Outpu layer:\n", w,"and weight shape: \n",w.shape)
print("Bias of Outpu layer :\n",b,"\nBias Shape:\n",b.shape)



Weights of hidden 1 layer:
 [[8. 8. 5. 6. 0. 8. 0. 3. 2. 2.]
 [0. 0. 6. 3. 1. 1. 4. 6. 2. 9.]
 [7. 6. 7. 1. 2. 7. 3. 5. 0. 7.]
 [7. 4. 5. 8. 8. 1. 1. 2. 3. 0.]
 [4. 6. 5. 6. 5. 2. 5. 9. 1. 1.]] and weight shape: 
 (5, 10)
Bias of hidden 1 layer :
 [1. 2. 1. 2. 1. 2. 1. 2. 1. 2.] 
Bias Shape:
 (10,)
Weights of hidden 2 layer:
 [[7. 4. 2.]
 [4. 6. 0.]
 [2. 8. 5.]
 [0. 3. 5.]
 [3. 9. 2.]
 [4. 1. 2.]
 [4. 9. 5.]
 [8. 7. 6.]
 [0. 9. 9.]
 [5. 3. 6.]] and weight shape: 
 (10, 3)
Bias of hidden 2 layer :
 [1. 2. 1.] 
Bias Shape:
 (3,)
Weights of Outpu layer:
 [[0.]
 [5.]
 [4.]] and weight shape: 
 (3, 1)
Bias of Outpu layer :
 [7.] 
Bias Shape:
 (1,)
